[package]
name = "uranus"
version = "0.1.0"
authors = ["Alexey Ivanov <alexeyivanov1861@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"